### ISSUE TITLE
Sort Challenge (2018082)

### ISSUE THREAD

**Issue by jossmac** [Thinkmill/code-challenge#30]
Hello!

Is there a reason we're doing `selection sort` and `merge sort`, rather than some other flavour like `bubble sort`?

**Comment by timleslie** [comment]
Hey Joss, the choice here was motivated by wanting to cover one each of an O(N^2) and an O(N*logN) algorithm. Since we covered bubble sort, selection sort and merge sort in my talk the other day we figured these would be good candidates to choose from. At that point the decision comes down to bubble vs selection sort for the O(N^2) algo, at which point selection sort won out largely due to my personal preference :-)

If you or anyone else is interested, I would highly encourage implementing bubble sort as well, and also perhaps researching insertion sort (O(N^2)) and quick sort (O(N*logN)) and having a go at these as well.

**Comment by dominikwilkowski** [comment]
Closing for the reason stated: `Tims preference`
